FROM node:18

WORKDIR /app

# explizit ARG deklarieren
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG DATABASE_URL
ARG ENCRYPTION_KEY

# ARGs als ENV Variablen setzen
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV DATABASE_URL=$DATABASE_URL
ENV ENCRYPTION_KEY=$ENCRYPTION_KEY

COPY . .

RUN corepack enable
RUN yarn install
RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]
